# Workflow to handle building the Unity SDK on android
name: Android Build

on:
  workflow_dispatch:
    inputs:
      operating_systems:
        description: 'CSV of VMs to run on'
        default: 'ubuntu-latest,windows-latest,macos-latest'
        required: true
      # Which version of Unity to use
      unity_version:
        description: 'Unity version'
        default: '2017.4.40f1'
        required: true
      # Linux uses a different number for its versions
      linux_unity_version:
        description: 'Linux Unity version'
        default: '2017.4.10f1'
        required: true

jobs:
  build_android:
    name: build-android-${{matrix.os}}
    runs-on: ${{matrix.os}}
    if: contains(${{ github.event.inputs.operating_systems }}, ${{matrix.os}})
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
        - os: windows-latest
          unity_version: ${{ github.event.inputs.unity_version }}
          unity_install_dir: /c/Program Files/Unity_${{ github.event.inputs.unity_version }}
        - os: macos-latest
          unity_version: ${{ github.event.inputs.unity_version }}
          unity_install_dir: /Applications/Unity_${{ github.event.inputs.unity_version }}
        - os: ubuntu-latest
          unity_version: ${{ github.event.inputs.linux_unity_version }}
          unity_install_dir: /opt/unity-editor-${{ github.event.inputs.linux_unity_version }}

    env:
      # LC_ALL, LANG and U3D_PASSWORD are needed for U3D.
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      U3D_PASSWORD: ""
  
    steps:
      - name: Checkout Unity Repo
        uses: actions/checkout@v2
        with:
          submodules: true
          
      - name: Checkout CPP Repo
        uses: actions/checkout@v2
        with:
          repository: firebase/firebase-cpp-sdk
          path: firebase-cpp-sdk
          submodules: true

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install prerequisites
        shell: bash
        run: |
          echo "FIREBASE_CPP_SDK_DIR=${{ github.workspace }}/firebase-cpp-sdk" >> $GITHUB_ENV
          cd firebase-cpp-sdk
          python scripts/gha/install_prereqs_desktop.py
          build_scripts/android/install_prereqs.sh
          cd ..

      - name: Install Unity installer (U3D)
        shell: bash
        run: gem install u3d

      - name: Install python deps
        shell: bash
        run: |
          pip install -r scripts/gha/requirements.txt
      
      - name: Install Unity
        shell: bash
        run: |
          python scripts/gha/unity_installer.py --install --platforms "Android" --version ${{ matrix.unity_version }}
      
      - name: Setup Unity path
        shell: bash
        run: |
          echo "UNITY_ROOT_DIR=${{ matrix.unity_install_dir }}" >> $GITHUB_ENV

      - name: Build SDK (Android)
        shell: bash
        run: |
          ./build_android.sh

      - name: Upload Build
        uses: actions/upload-artifact@v2
        with:
          name: android_build
          path: android_build/*.zip
